version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
        requires:
          filters:
            branches:
              only: master