# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Felipe Luis
subtitle: Web Designer and Developer
description: I work with web designer, development and am freelancer
keywords: 'blog, job, dev, developer, freelancer, freela, web, designer, web designer,
desenvolvimento, fullstack, front-end, frontend, backend, back-end, php, jquery, laravel, npm, gulp, sass, css'
author: Felipe Luis
language: en
timezone:

metadata:
  author_id: defaultAuthorId
  language: en

# Minifier
all_minifier: true
js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false
  silent: false

js_minifier:
  enable: true
  mangle: true
  silent: false
  output:
  compress:
  exclude:
    - '*.min.js'

html_minifier:
  enable: true
  ignore_error: false
  silent: false
  exclude:

css_minifier:
  enable: true
  silent: false
  exclude:
    - '*.min.css'

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false

# Breadcrumb
breadcrumb:
  display: false

# Generate categories from directory-tree
# Dependencies: https://github.com/xu-song/hexo-auto-category
# depth: the depth of directory-tree you want to generate, should > 0
auto_category:
 enable: true
 depth:
categories:
  - web
  - framework

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www1.felipeluis.com.br/blog/
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 0
  loading: { enabled: true, style: 'wave', color: '#f78769' }
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
lazyload:
  enable: true
  # thumbPath: '/images/thumb'
  # className: #optional e.g. .J-lazyload-img
  # loadingImg: #optional eg. /images/loading.png

## Plugins: https://hexo.io/plugins/
# Themes: https://hexo.io/themes/
theme: bootstrap-blog
# theme: clean-blog
# theme: landscape

# Header
menu:
  - Home: /
  - Archives: /archives
  - Tags: /tags
  - Categories: /categories

# Title on top left of menu. Leave empty to use main blog title
menu_title: Configurable Title

# URL of the Home page image
index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg

# Default post title
default_post_title: Untitled


# navbar_brand: true
# menu:
#   Home: index.html
#   Archives: archives/
#   Bom dia: bom-dia/
#   About: about/
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
- about         # See also: `about_content`
- category
- tag
- tagcloud
- archives
- recent_posts
about_widget_content: >
  <p>I work with web designer, development and am freelancer.</p>

# Miscellaneous
google_analytics:

theme_config:
favicon: images/favicon.ico

twitter:
google_plus:

photos:               # displays a Bootstrap thumbnail gallery
- images/HNCK0537.jpg
- images/HNCK6173.jpg

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/felipelssilva/felipeluis.git
  branch: blog
  message: Blog - Updated {{ now('YYYY-MM-DD HH:mm:ss') }}
  name: felipelssilva
  email: felipeluis.6@gmail.com
  extend_dirs: /
  ignore_hidden: false # default is true
  ignore_pattern: regexp  # whatever file that matches the regexp will be ignored when deploying

# hexo-admin authentification
admin:
  username: fikipi
  password_hash: $2a$10$Pv/l13y5DU17AqLYrWK8EOO1.0KDlJdaD/HnU25oC.PUPCoJSIlMu
  secret: Nick is my cat

# PWA
pwa:
  manifest:
    path: /blog/manifest.json
    body:
      name: hexo
      short_name: hexo
      icons:
        - src: /images/android-chrome-192x192.png
          sizes: 192x192
          type: image/png
  serviceWorker:
    path: /blog/service-worker.js
    preload:
      urls:
        - /
      posts: 5
    opts:
      networkTimeoutSeconds: 5
    routes:
      - pattern: !!js/regexp /hm.baidu.com/
        strategy: networkOnly
      - pattern: !!js/regexp /.*\.(js|css|jpg|jpeg|png|gif)$/
        strategy: cacheFirst
      - pattern: !!js/regexp /\//
        strategy: networkFirst
  priority: 5
